import type { CatalogComponent } from "./platform-knowledge/types.js";

export const AWS_COMPONENTS: CatalogComponent[] = [
  {
    id: "redshift",
    label: "Amazon Redshift",
    category: "storage",
    platform: "aws",
    description: "Petabyte-scale cloud data warehouse for analytics and BI.",
    icon_key: "aws-redshift",
    color: "#FF9900",
    best_practices: ["Use RA3 nodes for compute/storage separation", "Enable concurrency scaling for peak workloads"],
  },
  {
    id: "api-gateway",
    label: "API Gateway",
    category: "networking",
    platform: "aws",
    description: "Managed API entry point with auth, throttling, and monitoring.",
    icon_key: "aws-api-gateway",
    color: "#FF9900",
    best_practices: ["Enable WAF integration", "Use usage plans for rate limiting"],
  },
  {
    id: "lambda",
    label: "AWS Lambda",
    category: "compute",
    platform: "aws",
    description: "Serverless compute for event-driven workloads.",
    icon_key: "aws-lambda",
    color: "#FF9900",
    best_practices: ["Right-size memory for CPU allocation", "Use provisioned concurrency for latency-sensitive paths"],
  },
  {
    id: "rds",
    label: "Amazon RDS",
    category: "storage",
    platform: "aws",
    description: "Managed relational database service.",
    icon_key: "aws-rds",
    color: "#FF9900",
    best_practices: ["Enable Multi-AZ for production", "Use read replicas for scaling reads"],
  },
  {
    id: "s3",
    label: "Amazon S3",
    category: "storage",
    platform: "aws",
    description: "Object storage for data lakes and static assets.",
    icon_key: "aws-s3",
    color: "#FF9900",
    best_practices: ["Enable versioning for critical buckets", "Use lifecycle policies for cost optimization"],
  },
  {
    id: "glue",
    label: "AWS Glue",
    category: "orchestration",
    platform: "aws",
    description: "Serverless ETL and data catalog for lakehouse pipelines.",
    icon_key: "aws-glue",
    color: "#FF9900",
    best_practices: ["Use Glue Data Catalog with Lake Formation", "Enable job bookmarks for incremental loads"],
  },
  {
    id: "kinesis",
    label: "Amazon Kinesis",
    category: "ingestion",
    platform: "aws",
    description: "Real-time streaming data ingestion and processing.",
    icon_key: "aws-kinesis",
    color: "#FF9900",
    best_practices: ["Right-size shards for throughput", "Use enhanced fan-out for multiple consumers"],
  },
  {
    id: "cloudwatch",
    label: "CloudWatch",
    category: "observability",
    platform: "aws",
    description: "Monitoring, logging, and alerting for AWS resources.",
    icon_key: "aws-cloudwatch",
    color: "#FF9900",
    best_practices: ["Set up dashboards per service", "Configure alarms for SLO breaches"],
  },
  {
    id: "ec2",
    label: "Amazon EC2",
    category: "compute",
    platform: "aws",
    description: "Scalable virtual compute instances.",
    icon_key: "aws-ec2",
    color: "#FF9900",
    best_practices: ["Use Auto Scaling groups", "Prefer Graviton for cost efficiency"],
  },
  {
    id: "dynamodb",
    label: "Amazon DynamoDB",
    category: "storage",
    platform: "aws",
    description: "Serverless NoSQL database for single-digit millisecond performance.",
    icon_key: "aws-dynamodb",
    color: "#FF9900",
    best_practices: ["Design partition keys for even distribution", "Use on-demand for variable workloads"],
  },
  {
    id: "waf",
    label: "AWS WAF",
    category: "security",
    platform: "aws",
    description: "Web application firewall for API and CloudFront protection.",
    icon_key: "aws-waf",
    color: "#FF9900",
    best_practices: ["Attach to API Gateway and ALB", "Use AWS Managed Rules as baseline"],
  },
  {
    id: "sqs",
    label: "Amazon SQS",
    category: "integration",
    platform: "aws",
    description: "Managed message queuing for decoupled architectures.",
    icon_key: "aws-sqs",
    color: "#FF9900",
    best_practices: ["Use dead-letter queues", "Prefer standard queues unless ordering is required"],
  },
];
