import type { ArchitectureGraph } from "../schema/graph.js";

function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, "_");
}

export function exportToMermaid(graph: ArchitectureGraph): string {
  const lines: string[] = ["```mermaid", "flowchart TB"];

  for (const zone of graph.zones ?? []) {
    lines.push(`  subgraph ${sanitizeId(zone.id)}["${zone.label}"]`);
    const zoneNodes = graph.nodes.filter((n) => n.zone_id === zone.id);
    for (const node of zoneNodes) {
      lines.push(`    ${sanitizeId(node.id)}["${node.label}"]`);
    }
    lines.push("  end");
  }

  const unzoned = graph.nodes.filter((n) => !n.zone_id);
  for (const node of unzoned) {
    lines.push(`  ${sanitizeId(node.id)}["${node.label}"]`);
  }

  for (const edge of graph.edges) {
    const label = edge.protocol_or_flow ? `|${edge.protocol_or_flow}|` : "";
    lines.push(`  ${sanitizeId(edge.from)} -->${label} ${sanitizeId(edge.to)}`);
  }

  lines.push("```");
  return lines.join("\n");
}

function tfSanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, "_");
}

export function exportToTerraformStub(graph: ArchitectureGraph): string {
  const platform = graph.platform ?? "generic";
  const lines: string[] = [
    `# Terraform stub for: ${graph.title ?? "Architecture"}`,
    `# Platform: ${platform}`,
    `# Generated by Architecture AI Studio`,
    "",
    'terraform {',
    '  required_version = ">= 1.5.0"',
    "}",
    "",
  ];

  for (const node of graph.nodes) {
    if (node.required_level === "optional") continue;
    lines.push(`# ${node.label} (${node.category})`);
    lines.push(`# ${node.description}`);
    lines.push(`# resource "${platform}_${node.category}" "${tfSanitizeId(node.id)}" {`);
    lines.push(`#   name = "${node.label}"`);
    lines.push("# }");
    lines.push("");
  }

  return lines.join("\n");
}
