import type { DataModelPackage } from "../schema/data-model.js";
import type { ArchitectureGraph } from "../schema/graph.js";

export function exportToDbtStub(model: DataModelPackage): string {
  const lines = [
    "-- dbt project stub generated by Architecture AI Studio",
    `-- domain: ${model.domain}`,
    `-- business_process: ${model.business_process}`,
    "",
  ];

  for (const dim of model.dimensional.dimensions) {
    lines.push(`-- models/gold/${dim.name}.sql`);
    lines.push(`{{ config(materialized='table', schema='gold') }}`);
    lines.push(`-- ${dim.explanation.business_purpose}`);
    lines.push(`-- grain: ${dim.explanation.grain}`);
    lines.push("SELECT");
    for (const col of dim.columns) {
      lines.push(`  NULL AS ${col.name}, -- ${col.data_type}`);
    }
    lines.push("FROM {{ ref('silver_conformed') }}");
    lines.push("");
  }

  for (const fact of model.dimensional.facts) {
    lines.push(`-- models/gold/${fact.name}.sql`);
    lines.push(`{{ config(materialized='table', schema='gold') }}`);
    lines.push(`-- ${fact.explanation.business_purpose}`);
    lines.push(`-- grain: ${fact.explanation.grain}`);
    lines.push("SELECT");
    for (const col of fact.columns) {
      lines.push(`  NULL AS ${col.name}, -- ${col.data_type}`);
    }
    lines.push("FROM {{ ref('silver_conformed') }}");
    lines.push("");
  }

  return lines.join("\n");
}

export function exportToAdfPipelineStub(graph: ArchitectureGraph): string {
  const ingestion = graph.nodes.find((n) => n.category === "ingestion");
  const storage = graph.nodes.filter((n) => n.category === "storage");

  return JSON.stringify(
    {
      name: `${graph.title ?? "architecture"}_adf_pipeline`,
      properties: {
        description: "ADF pipeline stub generated by Architecture AI Studio",
        activities: [
          {
            name: "CopySourceToLanding",
            type: "Copy",
            dependsOn: [],
            policy: { timeout: "01:00:00" },
            typeProperties: {
              source: { type: "SqlSource", query: "-- source query" },
              sink: { type: "ParquetSink", storeSettings: { type: "AzureBlobStorageReadSettings" } },
            },
          },
          ...(storage.length > 0
            ? [
                {
                  name: "TriggerDatabricksNotebook",
                  type: "DatabricksNotebook",
                  dependsOn: [{ activity: "CopySourceToLanding", dependencyConditions: ["Succeeded"] }],
                  typeProperties: {
                    notebookPath: "/Shared/medallion/transform",
                    baseParameters: { landing_path: "@pipeline().parameters.landing_path" },
                  },
                },
              ]
            : []),
        ],
        parameters: {
          landing_path: { type: "String", defaultValue: "abfss://landing/" },
        },
        annotations: [
          { key: "ingestion_component", value: ingestion?.label ?? "ADF Copy" },
          { key: "generated_by", value: "architecture-ai-studio" },
        ],
      },
    },
    null,
    2
  );
}

export function exportToDatabricksWorkflowStub(graph: ArchitectureGraph): string {
  const tasks = graph.nodes
    .filter((n) => ["ingestion", "storage", "orchestration", "compute"].includes(n.category))
    .map((node, i) => ({
      task_key: node.id.replace(/[^a-z0-9_]/gi, "_"),
      description: node.description,
      depends_on: i > 0 ? [{ task_key: graph.nodes.filter((n) => ["ingestion", "storage", "orchestration", "compute"].includes(n.category))[i - 1]?.id.replace(/[^a-z0-9_]/gi, "_") }] : [],
      notebook_task: {
        notebook_path: `/Shared/architecture-ai/${node.id}`,
        base_parameters: { component: node.label },
      },
    }));

  return JSON.stringify(
    {
      name: `${graph.title ?? "architecture"}_workflow`,
      tasks,
      schedule: { quartz_cron_expression: "0 0 6 * * ?", timezone_id: "UTC" },
      tags: { generated_by: "architecture-ai-studio", platform: graph.platform ?? "databricks" },
    },
    null,
    2
  );
}
