import type { PlatformKnowledge } from "./types.js";

export const DATABRICKS_KNOWLEDGE: PlatformKnowledge = {
  platform: "databricks",
  display_name: "Databricks",
  version: "2026.06",
  last_updated: "2026-06-09",
  doc_sources: [
    "https://docs.databricks.com/aws/en/ai-bi/release-notes/2026",
    "https://www.databricks.com/blog/next-generation-databricks-genie",
    "https://docs.databricks.com/en/lakehouse-architecture/",
  ],
  components: [
    {
      id: "auto-loader",
      label: "Auto Loader",
      category: "ingestion",
      platform: "databricks",
      description: "Incremental ingestion from cloud storage with schema inference.",
      icon_key: "databricks-auto-loader",
      color: "#FF3621",
      best_practices: [
        "Use checkpoint location for exactly-once ingestion",
        "Enable schema evolution for evolving sources",
      ],
    },
    {
      id: "delta-lake",
      label: "Delta Lake",
      category: "storage",
      platform: "databricks",
      description: "ACID transactions, time travel, and schema enforcement on data lakes.",
      icon_key: "databricks-delta-lake",
      color: "#FF3621",
      best_practices: [
        "Enable OPTIMIZE and liquid clustering for query performance",
        "Use medallion layering (bronze/silver/gold)",
      ],
    },
    {
      id: "unity-catalog",
      label: "Unity Catalog",
      category: "governance",
      platform: "databricks",
      description: "Unified governance for data and AI assets across workspaces.",
      icon_key: "databricks-unity-catalog",
      color: "#FF3621",
      best_practices: [
        "One metastore per cloud region",
        "Use fine-grained access controls, lineage, and auditing",
      ],
    },
    {
      id: "databricks-sql",
      label: "Databricks SQL Warehouse",
      category: "serving",
      platform: "databricks",
      description: "Serverless SQL compute for BI and ad-hoc analytics.",
      icon_key: "databricks-sql",
      color: "#FF3621",
      best_practices: [
        "Right-size warehouse for concurrency needs",
        "Use query federation for cross-source joins",
      ],
    },
    {
      id: "genie",
      label: "AI/BI Genie",
      category: "genai",
      platform: "databricks",
      description:
        "Conversational AI interface for natural-language analytics across governed data assets.",
      icon_key: "databricks-genie",
      color: "#FF3621",
      best_practices: [
        "Curate Genie Spaces with certified metrics and domain guardrails",
        "Use benchmarks and Inspect to validate SQL accuracy before production",
        "Route MCP and external connectors through Unity AI Gateway",
      ],
    },
    {
      id: "genie-spaces",
      label: "Genie Spaces",
      category: "genai",
      platform: "databricks",
      description:
        "Curated semantic experiences with knowledge stores, verified metric logic, and domain guardrails.",
      icon_key: "databricks-genie-spaces",
      color: "#FF3621",
      best_practices: [
        "Add column-level synonyms, joins, and certified metrics to the knowledge store",
        "Export Genie Space context as metric views for reusable semantics",
        "Pin trusted dashboards and apps as high-trust routing sources",
      ],
    },
    {
      id: "genie-agent-mode",
      label: "Genie Agent Mode",
      category: "genai",
      platform: "databricks",
      description:
        "Iterative agentic reasoning that plans, explores hypotheses, runs multiple SQL queries, and reflects on results.",
      icon_key: "databricks-genie-agent",
      color: "#FF3621",
      best_practices: [
        "Use for multi-step 'why' and 'how' questions, not simple lookups",
        "Ensure Unity Catalog metadata and author-defined semantics are complete",
        "Review generated SQL and citations before acting on conclusions",
      ],
    },
    {
      id: "genie-ontology",
      label: "Genie Ontology",
      category: "governance",
      platform: "databricks",
      description:
        "Auto-built business knowledge map from dashboards, notebooks, and pipelines to improve discovery and accuracy.",
      icon_key: "databricks-genie-ontology",
      color: "#FF3621",
      best_practices: [
        "Keep source dashboards and notebooks well-documented for ontology extraction",
        "Validate ontology rankings against domain expert expectations",
      ],
    },
    {
      id: "genie-mcp",
      label: "Genie Managed MCP Server",
      category: "integration",
      platform: "databricks",
      description:
        "Managed MCP bridge for agents to query Genie Spaces and Unity Catalog data with grounded answers.",
      icon_key: "databricks-genie-mcp",
      color: "#FF3621",
      best_practices: [
        "Govern MCP access via Unity AI Gateway",
        "Use for cross-system agents that need natural-language data access",
      ],
    },
    {
      id: "mlflow",
      label: "MLflow",
      category: "observability",
      platform: "databricks",
      description: "ML lifecycle management with tracing and evaluation for GenAI.",
      icon_key: "databricks-mlflow",
      color: "#FF3621",
      best_practices: [
        "Trace all GenAI calls in production",
        "Use custom scorers and human review loops for agent evaluation",
      ],
    },
    {
      id: "ai-gateway",
      label: "Unity AI Gateway",
      category: "genai",
      platform: "databricks",
      description: "Governed routing for LLM endpoints, agents, MCP servers, and external connectors.",
      icon_key: "databricks-ai-gateway",
      color: "#FF3621",
      best_practices: [
        "Route all LLM and MCP traffic through the gateway",
        "Enable audit logging, rate limits, and access control",
      ],
    },
    {
      id: "dlt",
      label: "Delta Live Tables",
      category: "orchestration",
      platform: "databricks",
      description: "Declarative ETL pipelines with built-in data quality expectations.",
      icon_key: "databricks-dlt",
      color: "#FF3621",
      best_practices: [
        "Define expectations for data quality gates between medallion layers",
        "Use for bronze → silver → gold transformations",
      ],
    },
    {
      id: "model-serving",
      label: "Model Serving",
      category: "serving",
      platform: "databricks",
      description: "Real-time and batch model inference endpoints.",
      icon_key: "databricks-model-serving",
      color: "#FF3621",
      best_practices: [
        "Enable auto-scaling for variable traffic",
        "Use GPU instances for large models",
      ],
    },
    {
      id: "vector-search",
      label: "Vector Search",
      category: "storage",
      platform: "databricks",
      description: "Managed vector index for RAG and semantic retrieval over Unity Catalog data.",
      icon_key: "databricks-vector-search",
      color: "#FF3621",
      best_practices: [
        "Sync indexes from governed Delta tables",
        "Combine with AI Gateway for governed retrieval-augmented generation",
      ],
    },
    {
      id: "agent-bricks",
      label: "Agent Bricks",
      category: "genai",
      platform: "databricks",
      description: "Pre-built agent components for common enterprise AI patterns on Databricks.",
      icon_key: "databricks-agent-bricks",
      color: "#FF3621",
      best_practices: [
        "Compose agents with Unity Catalog-governed tools",
        "Evaluate agent trajectories with MLflow tracing",
      ],
    },
  ],
  techniques: [
    {
      id: "genie-knowledge-store",
      name: "Genie Knowledge Store",
      category: "genai",
      description:
        "Living semantic model with column synonyms, joins, certified metrics, and table-level context.",
      when_to_use: "Natural-language BI, self-serve analytics, or conversational data access",
      best_practices: [
        "Codify business logic via SQL expressions or trusted functions",
        "Maintain benchmark suites for regression testing",
        "Export space context as metric views for reuse",
      ],
      related_components: ["genie", "genie-spaces", "unity-catalog"],
      added_in_version: "2025.12",
      doc_url: "https://www.databricks.com/blog/aibi-genie-now-generally-available",
    },
    {
      id: "genie-agent-mode",
      name: "Genie Agent Mode",
      category: "genai",
      description:
        "Multi-step iterative reasoning: plan → explore → SQL → reflect → report with visualizations.",
      when_to_use: "Complex 'why' and 'how' questions spanning multiple data domains",
      best_practices: [
        "Provide rich Unity Catalog metadata for hypothesis testing",
        "Use Inspect to verify SQL before trusting agent conclusions",
        "Scale reasoning depth to question complexity",
      ],
      related_components: ["genie-agent-mode", "genie-spaces", "databricks-sql"],
      added_in_version: "2026.04",
    },
    {
      id: "genie-deep-research",
      name: "Genie Deep Research",
      category: "genai",
      description:
        "Research-plan-driven mode that tests multiple hypotheses in parallel for open-ended analysis.",
      when_to_use: "Strategic analysis like churn drivers, campaign optimization, or root-cause investigation",
      best_practices: [
        "Require citations and one-click scrutiny of intermediate work",
        "Ground on Genie knowledge store for trustworthy conclusions",
      ],
      related_components: ["genie", "genie-agent-mode"],
      added_in_version: "2026.02",
    },
    {
      id: "genie-inspect",
      name: "Genie Inspect",
      category: "genai",
      description:
        "Review generated SQL, run verification queries, and iteratively improve answer accuracy.",
      when_to_use: "Production Genie Spaces where SQL accuracy is critical",
      best_practices: [
        "Author smaller verification queries for key metrics",
        "Use as part of space authoring workflow before publishing",
      ],
      related_components: ["genie-spaces"],
      added_in_version: "2026.03",
    },
    {
      id: "genie-ontology",
      name: "Genie Ontology",
      category: "governance",
      description:
        "Automatically extracts and ranks business knowledge from dashboards, notebooks, and pipelines.",
      when_to_use: "Large workspaces where manual knowledge curation does not scale",
      best_practices: [
        "Keep source assets well-annotated for better extraction",
        "Validate ontology against domain benchmarks",
      ],
      related_components: ["genie-ontology", "unity-catalog"],
      added_in_version: "2026.05",
    },
    {
      id: "specialized-knowledge-search",
      name: "Specialized Knowledge Search",
      category: "genai",
      description:
        "Semantic asset discovery using workspace tables, notebooks, dashboards, and documents.",
      when_to_use: "Enterprise data agents that must find the right tables and metrics",
      best_practices: [
        "Maintain rich metadata signals on all data assets",
        "Use parallel search indices for table and document discovery",
      ],
      related_components: ["genie", "unity-catalog", "vector-search"],
      added_in_version: "2025.11",
    },
    {
      id: "multi-llm-agent-design",
      name: "Multi-LLM Agent Design",
      category: "genai",
      description:
        "Different optimized LLMs for planning, search, code generation, and judging sub-tasks.",
      when_to_use: "Production GenAI agents where accuracy, cost, and latency must be balanced",
      best_practices: [
        "Assign models per sub-agent responsibility",
        "Trace and evaluate each sub-agent with MLflow",
      ],
      related_components: ["genie", "mlflow", "ai-gateway"],
      added_in_version: "2025.11",
    },
    {
      id: "medallion-architecture",
      name: "Medallion Architecture",
      category: "storage",
      description: "Bronze → Silver → Gold incremental data quality progression on Delta Lake.",
      when_to_use: "All lakehouse implementations on Databricks",
      best_practices: [
        "Keep bronze raw, silver conformed, gold business-ready",
        "Use DLT expectations between layers",
      ],
      related_components: ["delta-lake", "dlt", "auto-loader"],
      added_in_version: "2024.01",
    },
  ],
  templates: [
    {
      id: "medallion-lakehouse",
      name: "Medallion Lakehouse",
      description: "Bronze → Silver → Gold pipeline with Unity Catalog governance.",
      platform: "databricks",
      components: ["auto-loader", "delta-lake", "unity-catalog", "dlt", "databricks-sql"],
      techniques: ["medallion-architecture"],
    },
    {
      id: "genai-platform",
      name: "GenAI Platform",
      description: "RAG + agents with MLflow tracing, AI Gateway, and Vector Search.",
      platform: "databricks",
      components: ["ai-gateway", "mlflow", "model-serving", "vector-search", "unity-catalog"],
      techniques: ["multi-llm-agent-design"],
    },
    {
      id: "genie-analytics",
      name: "Genie Conversational Analytics",
      description:
        "Natural-language BI with Genie Spaces, Agent Mode, Ontology, and governed MCP access.",
      platform: "databricks",
      components: [
        "genie",
        "genie-spaces",
        "genie-agent-mode",
        "genie-ontology",
        "unity-catalog",
        "ai-gateway",
        "databricks-sql",
      ],
      techniques: [
        "genie-knowledge-store",
        "genie-agent-mode",
        "genie-inspect",
        "genie-ontology",
      ],
    },
    {
      id: "enterprise-data-agent",
      name: "Enterprise Data Agent",
      description:
        "Cross-system data agent with Genie MCP, specialized knowledge search, and AI Gateway governance.",
      platform: "databricks",
      components: ["genie-mcp", "genie", "ai-gateway", "unity-catalog", "mlflow"],
      techniques: ["specialized-knowledge-search", "multi-llm-agent-design", "genie-agent-mode"],
    },
  ],
  review_dimensions: [
    "Unity Catalog governance and lineage",
    "Medallion layering and data quality",
    "Genie Spaces knowledge store completeness",
    "Genie Agent Mode for complex analytics",
    "MLflow tracing and agent evaluation",
    "Unity AI Gateway for LLM/MCP governance",
    "Vector Search for RAG patterns",
    "MCP connector governance",
  ],
  generation_hints: [
    "Evaluate AI/BI Genie and Genie Spaces for natural-language analytics needs",
    "Use Genie Agent Mode for multi-step 'why/how' business questions",
    "Apply Genie Knowledge Store with certified metrics and column-level context",
    "Enable Genie Ontology for automatic business knowledge extraction",
    "Route Genie MCP and external connectors through Unity AI Gateway",
    "Use Genie Inspect and benchmarks to validate SQL accuracy",
    "Consider Genie Deep Research for hypothesis-driven strategic analysis",
    "Apply medallion architecture (bronze/silver/gold) with Delta Live Tables",
    "Govern all data and AI assets through Unity Catalog",
    "Instrument GenAI agents with MLflow tracing and evaluation",
  ],
  changelog: [
    {
      version: "2026.06",
      date: "2026-06-09",
      summary: "Added Genie advanced techniques, Ontology, Agent Mode, MCP, and knowledge registry",
      additions: [
        "Genie Agent Mode",
        "Genie Ontology",
        "Genie Managed MCP Server",
        "Genie Inspect",
        "Genie Deep Research",
        "Enterprise Data Agent template",
      ],
    },
    {
      version: "2026.04",
      date: "2026-04-01",
      summary: "Next-generation unified Genie with certified spaces and MCP via AI Gateway",
      additions: ["Unified Genie chat", "Certified Genie Spaces routing", "MCP via AI Gateway"],
    },
  ],
};
